// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0YPupJyMkbu47rlqtARrOm99jHD3E7k',
    appId: '1:189798641031:web:256d24def0008d73e0f722',
    messagingSenderId: '189798641031',
    projectId: 'digital-bookshelf-beb42',
    authDomain: 'digital-bookshelf-beb42.firebaseapp.com',
    storageBucket: 'digital-bookshelf-beb42.firebasestorage.app',
    measurementId: 'G-4F3DWZ47XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKFyH_T3I_MTn76uLtdv4boJJRv4vLSF8',
    appId: '1:189798641031:android:67b3ca21bc41526de0f722',
    messagingSenderId: '189798641031',
    projectId: 'digital-bookshelf-beb42',
    storageBucket: 'digital-bookshelf-beb42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_EVu7dSeWvVj479zRwAuWUWB64FQ2wQ',
    appId: '1:189798641031:ios:004b5f55d3854a66e0f722',
    messagingSenderId: '189798641031',
    projectId: 'digital-bookshelf-beb42',
    storageBucket: 'digital-bookshelf-beb42.firebasestorage.app',
    iosBundleId: 'com.example.digitalBookshelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_EVu7dSeWvVj479zRwAuWUWB64FQ2wQ',
    appId: '1:189798641031:ios:004b5f55d3854a66e0f722',
    messagingSenderId: '189798641031',
    projectId: 'digital-bookshelf-beb42',
    storageBucket: 'digital-bookshelf-beb42.firebasestorage.app',
    iosBundleId: 'com.example.digitalBookshelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI0YPupJyMkbu47rlqtARrOm99jHD3E7k',
    appId: '1:189798641031:web:c421121b2061daa9e0f722',
    messagingSenderId: '189798641031',
    projectId: 'digital-bookshelf-beb42',
    authDomain: 'digital-bookshelf-beb42.firebaseapp.com',
    storageBucket: 'digital-bookshelf-beb42.firebasestorage.app',
    measurementId: 'G-9Q354G0H9H',
  );
}
